'use strict';

export const LIST_HOT_COLUMNS = 'LIST_HOT_COLUMNS';
export const LIST_COLUMNS = 'LIST_COLUMNS';
export const VIEW_COLUMN = 'VIEW_COLUMN';
export const RELOADED = 'RELOADED';
export const GLOBAL = 'GLOBAL';
export const LIST_COLUMN_SEARCH_TAGS = 'LIST_COLUMN_SEARCH_TAGS';
export const TOGGLE_COLUMN_SEARCH_TAG = 'TOGGLE_COLUMN_SEARCH_TAG';
export const ADD_USER_INFO = 'ADD_USER_INFO';
export const VALIDATE_USER_INFO = 'VALIDATE_USER_INFO';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const SEND_FORGET_PASSWORD_EMAIL_RESULT = 'SEND_FORGET_PASSWORD_EMAIL_RESULT';
export const RESET_PASS_ADD = 'RESET_PASS_ADD';
export const RESET_PASS_VALIDATE = 'RESET_PASS_VALIDATE';
export const RESET_PASS_RESULT = 'RESET_PASS_RESULT';
export const LOGIN_RESULT = 'LOGIN_RESULT';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';
