'use strict';

export const LIST_HOT_COLUMNS = 'LIST_HOT_COLUMNS';
export const LIST_COLUMNS = 'LIST_COLUMNS';
export const VIEW_COLUMN = 'VIEW_COLUMN';
export const RELOADED = 'RELOADED';
export const GLOBAL = 'GLOBAL';
export const LIST_COLUMN_SEARCH_TAGS = 'LIST_COLUMN_SEARCH_TAGS';
export const TOGGLE_COLUMN_SEARCH_TAG = 'TOGGLE_COLUMN_SEARCH_TAG';
export const ADD_USER_INFO = 'ADD_USER_INFO';
export const VALIDATE_USER_INFO = 'VALIDATE_USER_INFO';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
